### PR TITLE
Update Person.cs

### PR DESCRIPTION
**Pull request by jwillmer**
Added weight field to person.

### CODE REVIEW

**Comment by miyconst** [comment]
Hm, I don't think `double` is a good data type for Weight. Maybe `int` or `decimal`?

**Comment by jwillmer** [comment]
For a person I think it is logical to use pound or killogram and I think ```decimal``` is way to big and with ```int``` you can not display the gramms. That is why I used double.

**Comment by miyconst** [comment]
The problem is that `double` losses accuracy when used in math expressions and this might cause some strange issues.

**Comment by jwillmer** [comment]
Now i switched to decimal :)

**Pull request merged**
